import { LitElement } from "lit";
import "./components/top-nav";
import "./components/audio-player";
export declare class FiniteLoops extends LitElement {
    private activeRegionIndex;
    private isDetailOpen;
    private _selectedRelease;
    private _icecastData;
    private _audioPlaying;
    private _audioTrack;
    private _isPlayerOpen;
    private _viewport;
    private _isNavigating;
    private _audioBus;
    private _pollTimer;
    private readonly regions;
    private get _activeRegion();
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _preventSelection;
    firstUpdated(): void;
    private _clampRegionIndex;
    private _setActiveRegion;
    private _syncHash;
    private _scrollViewportToRegion;
    private _goToRegion;
    private _scrollToRegion;
    private _handleKeyDown;
    private _cancelNavigating;
    private _handleWheel;
    private _handleScroll;
    private _handleNavRequest;
    private _toggleDetail;
    private _hydrateFromHash;
    private _fetchIcecastStatus;
    private _toggleRadio;
    private _onAudioChange;
    private _handleLogoClick;
    private _handleTogglePlayback;
    private _handleStopPlayback;
    private _formatUptime;
    private _getSources;
    private _renderRegionScene;
    static styles: import("lit").CSSResult;
    render(): import("lit").TemplateResult<1>;
    private _selectRelease;
    private _renderDetailContent;
    private _caretSvg;
    private _nextRegion;
    private _prevRegion;
}
