import { Pattern } from './types';
export declare class SequencerEngine {
    private patterns;
    private _playing;
    private _recording;
    private _currentStep;
    private _selectedSample;
    private _selectedStep;
    private _bpm;
    private audioContext;
    private schedulerInterval;
    private nextStepTime;
    private readonly scheduleAheadTime;
    private readonly lookaheadMs;
    onTick: ((step: number) => void) | null;
    onTrigger: ((padIndex: number, velocity: number, pitch: number, time: number) => void) | null;
    constructor(audioContext: AudioContext);
    start(): void;
    stop(): void;
    toggleRecording(): void;
    isPlaying(): boolean;
    isRecording(): boolean;
    getCurrentStep(): number;
    setBpm(bpm: number): void;
    private get stepDuration();
    setSelectedSample(padIndex: number): void;
    getSelectedSample(): number;
    selectStep(stepIndex: number | null): void;
    getSelectedStep(): number | null;
    getPattern(padIndex: number): Pattern;
    toggleStep(padIndex: number, stepIndex: number): void;
    setStepVelocity(padIndex: number, stepIndex: number, velocity: number): void;
    setStepPitch(padIndex: number, stepIndex: number, pitch: number): void;
    setPatternLength(padIndex: number, length: number): void;
    setPatternSwing(padIndex: number, swing: number): void;
    recordHit(padIndex: number): void;
    private scheduler;
    private scheduleStep;
    private advanceStep;
    dispose(): void;
}
